say -v 'Agnes' "Isn't it nice to have a computer that will talk to you?"
say -v 'Albert' "I have a frog in my throat. No, I mean a real frog!"
say -v 'Alex' "Most people recognize me by my voice."
say -v 'Alice' "Salve, mi chiamo Alice e sono una voce italiana."
say -v 'Alva' "Hej, jag heter Alva. Jag är en svensk röst."
say -v 'Amelie' "Bonjour, je m’appelle Amelie. Je suis une voix canadienne."
say -v 'Anna' "Hallo, ich heiße Anna und ich bin eine deutsche Stimme."
say -v 'Bad News' "The light you see at the end of the tunnel is the headlamp of a fast approaching train."
say -v 'Bahh' "Do not pull the wool over my eyes."
say -v 'Bells' "Time flies when you are having fun."
say -v 'Boing' "Spring has sprung, fall has fell, winter's here and it's colder than usual."
say -v 'Bruce' "I sure like being inside this fancy computer"
say -v 'Bubbles' "Pull the plug! I'm drowning!"
say -v 'Carmit' "שלום. קוראים לי כרמית, ואני קול בשפה העברית."
say -v 'Cellos' "Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo"
say -v 'Damayanti' "Halo, nama saya Damayanti. Saya berbahasa Indonesia."
say -v 'Daniel' "Hello, my name is Daniel. I am a British-English voice."
say -v 'Deranged' "I need to go on a really long vacation."
say -v 'Diego' "Hola, me llamo Diego y soy una voz española."
say -v 'Ellen' "Hallo, mijn naam is Ellen. Ik ben een Belgische stem."
say -v 'Fiona' "Hello, my name is Fiona. I am a Scottish-English voice."
say -v 'Fred' "I sure like being inside this fancy computer"
say -v 'Good News' "Congratulations you just won the sweepstakes and you don't have to pay income tax again."
say -v 'Hysterical' "Please stop tickling me!"
say -v 'Ioana' "Bună, mă cheamă Ioana . Sunt o voce românească."
say -v 'Joana' "Olá, chamo-me Joana e dou voz ao português falado em Portugal."
say -v 'Junior' "My favorite food is pizza."
say -v 'Kanya' "สวัสดีค่ะ ดิฉันชื่อKanya"
say -v 'Karen' "Hello, my name is Karen. I am an Australian-English voice."
say -v 'Kathy' "Isn't it nice to have a computer that will talk to you?"
say -v 'Kyoko' "こんにちは、私の名前はKyokoです。日本語の音声をお届けします。"
say -v 'Laura' "Ahoj. Volám sa Laura . Som hlas v slovenskom jazyku."
say -v 'Lekha' "नमस्कार, मेरा नाम लेखा है.Lekha मै हिंदी मे बोलने वाली आवाज़ हूँ."
say -v 'Luciana' "Olá, o meu nome é Luciana e a minha voz corresponde ao português que é falado no Brasil"
say -v 'Maged' "مرحبًا اسمي Maged. أنا عربي من السعودية."
say -v 'Mariska' "Üdvözlöm! Mariska vagyok. Én vagyok a magyar hang."
say -v 'Mei-Jia' "您好，我叫美佳。我說國語。"
say -v 'Melina' "Γεια σας, ονομάζομαι Melina. Είμαι μια ελληνική φωνή."
say -v 'Milena' "Здравствуйте, меня зовут Milena. Я – русский голос системы."
say -v 'Moira' "Hello, my name is Moira. I am an Irish-English voice."
say -v 'Monica' "Hola, me llamo Monica y soy una voz española."
say -v 'Nora' "Hei, jeg heter Nora. Jeg er en norsk stemme."
say -v 'Paulina' "Hola, me llamo Paulina y soy una voz mexicana."
say -v 'Pipe Organ' "We must rejoice in this morbid voice."
say -v 'Princess' "When I grow up I'm going to be a scientist."
say -v 'Ralph' "The sum of the squares of the legs of a right triangle is equal to the square of the hypotenuse."
say -v 'Samantha' "Hello, my name is Samantha. I am an American-English voice."
say -v 'Sara' "Hej, jeg hedder Sara. Jeg er en dansk stemme."
say -v 'Satu' "Hei, minun nimeni on Satu. Olen suomalainen ääni."
say -v 'Sin-ji' "您好，我叫 Sin-ji。我講廣東話。"
say -v 'Tessa' "Hello, my name is Tessa. I am a South African-English voice."
say -v 'Thomas' "Bonjour, je m’appelle Thomas. Je suis une voix française."
say -v 'Ting-Ting' "您好，我叫Ting-Ting。我讲中文普通话。"
say -v 'Trinoids' "We cannot communicate with these carbon units."
say -v 'Veena' "Hello, my name is Veena. I am an Indian-English voice."
say -v 'Vicki' "Isn't it nice to have a computer that will talk to you?"
say -v 'Victoria' "Isn't it nice to have a computer that will talk to you?"
say -v 'Whisper' "Pssssst, hey you, Yeah you, Who do ya think I'm talking to, the mouse?"
say -v 'Xander' "Hallo, mijn naam is Xander. Ik ben een Nederlandse stem."
say -v 'Yelda' "Merhaba, benim adım Yelda. Ben Türkçe bir sesim."
say -v 'Yuna' "안녕하세요. 제 이름은 Yuna입니다. 저는 한국어 음성입니다."
say -v 'Zarvox' "That looks like a peaceful planet."
say -v 'Zosia' "Witaj. Mam na imię Zosia, jestem głosem kobiecym dla języka polskiego."
say -v 'Zuzana' "Dobrý den, jmenuji se Zuzana. Jsem český hlas."
